---
title: "DiagrammeR-Generator"
author: "Alvin Chen"
date: "10/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Neural Network Graph

```{r}
library(DiagrammeR)
library(DiagrammeRsvg)
library(magrittr)
library(rsvg)

G <-'digraph G {
rankdir=LR
splines=line
nodesep=.05;

node [label=""];

subgraph cluster_0 {
color=white;
        node [style=solid,color=blue4, shape=circle];
x1 x2 x3;
label = "layer 1";
}

subgraph cluster_1 {
color=white;
node [style=solid,color=red2, shape=circle];
a12 a22 a32 a42 a52;
label = "layer 2";
}

subgraph cluster_2 {
color=white;
node [style=solid,color=red2, shape=circle];
a13 a23 a33 a43 a53;
label = "layer 3";
}

subgraph cluster_3 {
color=white;
node [style=solid,color=seagreen2, shape=circle];
O1 O2 O3 O4;
label="layer 4";
}

x1 -> a12;
x1 -> a22;
x1 -> a32;
x1 -> a42;
x1 -> a52;

x2 -> a12;
x2 -> a22;
x2 -> a32;
x2 -> a42;
x2 -> a52;

x3 -> a12;
x3 -> a22;
x3 -> a32;
x3 -> a42;
x3 -> a52;

a12 -> a13
a22 -> a13
a32 -> a13
a42 -> a13
a52 -> a13

a12 -> a23
a22 -> a23
a32 -> a23
a42 -> a23
a52 -> a23

a12 -> a33
a22 -> a33
a32 -> a33
a42 -> a33
a52 -> a33

a12 -> a43
a22 -> a43
a32 -> a43
a42 -> a43
a52 -> a43

a12 -> a53
a22 -> a53
a32 -> a53
a42 -> a53
a52 -> a53

a13 -> O1
a23 -> O1
a33 -> O1
a43 -> O1
a53 -> O1

a13 -> O2
a23 -> O2
a33 -> O2
a43 -> O2
a53 -> O2

a13 -> O3
a23 -> O3
a33 -> O3
a43 -> O3
a53 -> O3

a13 -> O4
a23 -> O4
a33 -> O4
a43 -> O4
a53 -> O4



}'


grViz(G, width="100%")
# grViz(G, width=1500) %>%
#     export_svg %>% charToRaw %>% rsvg_png("test.png")

```


```{r}
G2 <- 'digraph G {
rankdir = LR;
splines=false;
edge[style=invis];
ranksep= 1.4;
{
node [shape=circle, color=yellow, style=filled, fillcolor=yellow];
x0 [label=<x<sub>0</sub>>]; 
a02 [label=<a<sub>0</sub><sup>(2)</sup>>]; 
a03 [label=<a<sub>0</sub><sup>(3)</sup>>];
}
{
node [shape=circle, color=chartreuse, style=filled, fillcolor=chartreuse];
x1 [label=<x<sub>1</sub>>];
x2 [label=<x<sub>2</sub>>]; 
x3 [label=<x<sub>3</sub>>];
}
{
node [shape=circle, color=dodgerblue, style=filled, fillcolor=dodgerblue];
a12 [label=<a<sub>1</sub><sup>(2)</sup>>];
a22 [label=<a<sub>2</sub><sup>(2)</sup>>];
a32 [label=<a<sub>3</sub><sup>(2)</sup>>];
a42 [label=<a<sub>4</sub><sup>(2)</sup>>];
a52 [label=<a<sub>5</sub><sup>(2)</sup>>];
a13 [label=<a<sub>1</sub><sup>(3)</sup>>];
a23 [label=<a<sub>2</sub><sup>(3)</sup>>];
a33 [label=<a<sub>3</sub><sup>(3)</sup>>];
a43 [label=<a<sub>4</sub><sup>(3)</sup>>];
a53 [label=<a<sub>5</sub><sup>(3)</sup>>];
}
{
node [shape=circle, color=coral1, style=filled, fillcolor=coral1];
O1 [label=<a<sub>1</sub><sup>(4)</sup>>];
O2 [label=<a<sub>2</sub><sup>(4)</sup>>]; 
O3 [label=<a<sub>3</sub><sup>(4)</sup>>]; 
O4 [label=<a<sub>4</sub><sup>(4)</sup>>];
}
{
  rank=same;
  x0->x1->x2->x3;
}
{
  rank=same;
  a02->a12->a22->a32->a42->a52;
}
{
  rank=same;
  a03->a13->a23->a33->a43->a53;
}
{
  rank=same;
  O1->O2->O3->O4;
}
a02->a03;  // prevent tilting
l0 [shape=plaintext, label="layer 1 (input layer)"];
l0->x0;
{rank=same; l0;x0};
l1 [shape=plaintext, label="layer 2 (hidden layer)"];
l1->a02;
{rank=same; l1;a02};
l2 [shape=plaintext, label="layer 3 (hidden layer)"];
l2->a03;
{rank=same; l2;a03};
l3 [shape=plaintext, label="layer 4 (output layer)"];
l3->O1;
{rank=same; l3;O1};
edge[style=solid, tailport=e, headport=w];
{x0; x1; x2; x3} -> {a12;a22;a32;a42;a52};
{a02;a12;a22;a32;a42;a52} -> {a13;a23;a33;a43;a53};
{a03;a13;a23;a33;a43;a53} -> {O1,O2,O3,O4};
}'
grViz(G2, width=1600, height=1200) %>%
export_svg %>% charToRaw %>% rsvg_png("./images/neural-network-sample.png", width=1600)
  
```